apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  # Write your values (for the initial superuser) as plain text here. No Base64 needed!
  POSTGRES_DB: appdb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: supersecretpassword