apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-pvc 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "200Mi"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-tier
  template:
    metadata:
      labels:
        app: db-tier
  spec:
      containers:
      - name: db-tier
        image: postgres:13
        envfiles:
          - name: db-env
            secretRef:
              secretName: db-secret
         
        ports:
          - containerPort: 5432
        volumeMounts:
          - name: init-sql
            mountPath: /docker-entrypoint-initdb.d
          - name: db-data
            mountPath: /var/lib/postgresql/data
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - appuser
            - -d
            - appdb
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - appuser
            - -d
            - appdb
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
    
    

      volumes:
        - name: init-sql
          configMap:
            name: init.sql
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db-tier
spec:
  selector:
    app: db-tier
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432