apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-tier
  template:
    metadata:
      labels:
        app: web-tier
    spec:
      initContainers:
      - name: web-tier-helper
        image: nginx:1.25.2-alpine
        command: ["sh", "-c" ]
        args: 
        -  |
           cp /tmp/default.conf /mnt/config/default.conf
           cp /tmp/index.html /mnt/html/index.html
        volumeMounts:
          - name: web-content
            mountPath: /tmp
          - name: nginx-configuration
            mountPath: /mnt/config
          - name: web-files
            mountPath: /mnt/html/
      containers:
      - name: web-tier
        image: nginx:1.25.2-alpine
        command: ["nginx", "-g", "daemon off;"]
        ports:
          - containerPort: 80
        volumeMounts:
          - name: web-content
            mountPath: /tmp
          - name: nginx-configuration
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
          - name: web-files
            mountPath: /usr/share/nginx/html/index.html
            subPath: index.html
      volumes:
        - name: web-content
          configMap:
            name: web-files
        - name: nginx-configuration
          emptyDir: {} 
        - name: web-files
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: web-tier 
spec:
  selector:
    app: web-tier
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80